// Bundles index.html (repo root) into html.ts so the Edge Function can serve the UI.
// Run from the repo root:  deno run --allow-read --allow-write supabase/functions/outreach-bot/bundle.ts
const html = await Deno.readTextFile("index.html");
const out = "// Regenerated by bundle.ts. Do not edit by hand.\nexport const HTML = " + JSON.stringify(html) + ";\n";
await Deno.writeTextFile("supabase/functions/outreach-bot/html.ts", out);
console.log("bundled", html.length, "bytes into supabase/functions/outreach-bot/html.ts");
