#!/bin/bash
# Deploy the Outreach Script Bot Edge Function to Supabase.
#
# Usage:
#   SUPABASE_TOKEN=sbp_xxx bash deploy.sh
#
# Optional (only needed the first time, or to rotate secrets):
#   ANTHROPIC_API_KEY=sk-ant-xxx   # Claude API key (stored as a Supabase secret)
#   ADMIN_KEY=xxx                  # shared admin key guarding the generate endpoint
#
# No secrets live in this repo — they are stored as Supabase Edge Function
# secrets and never reach the browser.

set -e

# Always run from the project root (this script's own folder), so it works no
# matter what directory you invoke it from.
cd "$(cd "$(dirname "$0")" && pwd)"

PROJECT_REF=pturxqgrhywyhylxovun

# ── Locate the Supabase CLI ───────────────────────────────────────────────────
SUPABASE=${SUPABASE:-}
if [ -z "$SUPABASE" ] || [ ! -x "$SUPABASE" ]; then
  for cand in "$(command -v supabase 2>/dev/null)" "$HOME/.local/bin/supabase"; do
    if [ -n "$cand" ] && [ -x "$cand" ]; then SUPABASE=$cand; break; fi
  done
fi
if [ -z "$SUPABASE" ] || [ ! -x "$SUPABASE" ]; then
  echo "ERROR: supabase CLI not found. Install it or set SUPABASE=/path/to/supabase"
  exit 1
fi

# ── Locate Deno (used to bundle index.html into the function) ────────────────
DENO=${DENO:-$HOME/.deno/bin/deno}
if [ ! -x "$DENO" ]; then
  if command -v deno >/dev/null 2>&1; then DENO=$(command -v deno); else
    echo "ERROR: Deno is required. Install: curl -fsSL https://deno.land/install.sh | sh"
    exit 1
  fi
fi

# ── Token check ───────────────────────────────────────────────────────────────
if [ -z "$SUPABASE_TOKEN" ]; then
  echo ""
  echo "  ERROR: SUPABASE_TOKEN is not set."
  echo "  Get a Personal Access Token at https://supabase.com/dashboard/account/tokens"
  echo "  Then run:  SUPABASE_TOKEN=sbp_xxx bash deploy.sh"
  echo ""
  exit 1
fi
export SUPABASE_ACCESS_TOKEN="$SUPABASE_TOKEN"

# ── Optionally (re)set secrets ────────────────────────────────────────────────
SECRETS=()
[ -n "$ANTHROPIC_API_KEY" ] && SECRETS+=("ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY")
[ -n "$ADMIN_KEY" ]         && SECRETS+=("ADMIN_KEY=$ADMIN_KEY")
[ -n "$NOTION_API_KEY" ]    && SECRETS+=("NOTION_API_KEY=$NOTION_API_KEY")
if [ ${#SECRETS[@]} -gt 0 ]; then
  echo "Setting secrets: $(printf '%s ' "${SECRETS[@]%%=*}")"
  $SUPABASE secrets set --project-ref $PROJECT_REF "${SECRETS[@]}"
fi

# ── Bundle index.html into the function ──────────────────────────────────────
echo "Bundling index.html into supabase/functions/outreach-bot/html.ts..."
$DENO eval "
const html = await Deno.readTextFile('index.html');
const out = '// Regenerated by deploy.sh. Do not edit.\nexport const HTML = ' + JSON.stringify(html) + ';\n';
await Deno.writeTextFile('supabase/functions/outreach-bot/html.ts', out);
console.log('  bundled', html.length, 'bytes');
"

# ── Deploy ────────────────────────────────────────────────────────────────────
echo ""
echo "Deploying outreach-bot..."
$SUPABASE functions deploy outreach-bot \
  --project-ref $PROJECT_REF \
  --no-verify-jwt

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  ✅ Done! The bot is live at:"
echo ""
echo "  https://$PROJECT_REF.supabase.co/functions/v1/outreach-bot"
echo ""
echo "  (open it once with ?admin=YOUR_ADMIN_KEY to save the key"
echo "   in your browser — same key as the offer bot)"
echo "════════════════════════════════════════════════════════════"
